### ISSUE TITLE
thread 'main' panicked at 'assertion failed: `(left != right)` while running example on Linux

### ISSUE THREAD

**Issue by VictorRandall** [libcala/stick#47]
I am on Linux Mint and i tried to run the example code, however i gave me an error saying:
```sh
thread 'main' panicked at 'assertion failed: `(left != right)`
  left: `-1`,
 right: `-1`', stick/src/raw/linux.rs:569:9
```

I also run with back trace and i gave me this:
```sh
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:145:5
   4: stick::raw::ffi::Controller::new
             at ./stick/src/raw/linux.rs:569:9
   5: stick::raw::ffi::Listener::controller
             at ./stick/src/raw/linux.rs:748:30
   6: <stick::raw::ffi::Listener as stick::raw::Listener>::poll
             at ./stick/src/raw/linux.rs:765:21
   7: <stick::listener::Listener as core::future::future::Future>::poll
             at ./stick/src/listener.rs:45:9
   8: <pasts::race::Event<F,G,V,S,T,Z> as core::future::future::Future>::poll
             at /home/victorrandall/.cargo/registry/src/github.com-1ecc6299db9ec823/pasts-0.8.0/src/race.rs:121:13
   9: <pasts::race::EventSlice<F,G,V,S,T,Z> as core::future::future::Future>::poll
             at /home/victorrandall/.cargo/registry/src/github.com-1ecc6299db9ec823/pasts-0.8.0/src/race.rs:68:38
  10: <pasts::race::Loop<S,T,F> as core::future::future::Future>::poll
             at /home/victorrandall/.cargo/registry/src/github.com-1ecc6299db9ec823/pasts-0.8.0/src/race.rs:202:41
  11: haptic::event_loop::{{closure}}
             at ./stick/examples/haptic.rs:62:21
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/future/mod.rs:80:19
  13: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/future/future.rs:119:9
  14: pasts::exec::Executor::block_on_pinned
             at /home/victorrandall/.cargo/registry/src/github.com-1ecc6299db9ec823/pasts-0.8.0/src/exec.rs:79:54
  15: pasts::exec::Executor::block_on
             at /home/victorrandall/.cargo/registry/src/github.com-1ecc6299db9ec823/pasts-0.8.0/src/exec.rs:100:9
  16: pasts::exec::block_on
             at /home/victorrandall/.cargo/registry/src/github.com-1ecc6299db9ec823/pasts-0.8.0/src/exec.rs:144:5
  17: haptic::main
             at ./stick/examples/haptic.rs:71:5
  18: core::ops::function::FnOnce::call_once
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
```

**Comment by AldaronLau** [comment]
@VictorRandall Thanks for opening this issue!

Noting that this has already being addressed in https://github.com/libcala/stick/pull/38
